/** @type {import('next').NextConfig} */
const nextConfig = {
    typescript: {
        // Ignore build errors for autogenerated services
        ignoreBuildErrors: true,
    },
};

module.exports = nextConfig;
