import type { Metadata } from 'next';
import { Poppins, Unbounded } from 'next/font/google';

import './globals.css';

import { validateEnv } from '@lib/env';
import Providers from '@src/providers';

const unbounded = Unbounded({
    weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    variable: '--font-unbounded',
});

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: '--font-poppins',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

if (process.env.NODE_ENV !== 'production') {
    validateEnv();
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={`${unbounded.className} ${poppins.variable}`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
