import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// These styles apply to every route in the application
import './globals.css';
import { validateEnv } from '@lib/env';
import { CSPostHogProvider } from '~/providers/PostHugProvider';
import { SignalRProvider } from '~/providers/SignalRProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

if (process.env.NODE_ENV !== 'production') {
  validateEnv();
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <CSPostHogProvider>
        <SignalRProvider>
          <body className={inter.className}>{children}</body>
        </SignalRProvider>
      </CSPostHogProvider>
    </html>
  );
}
